# Generated by Django 5.2.4 on 2025-07-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
