# Generated by Django 5.2.4 on 2025-08-05 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_category_flower_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flowers', to='flowers.category', verbose_name='Категория'),
        ),
    ]
