# Generated by Django 5.2.4 on 2025-08-08 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0008_alter_flower_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='in_stock',
        ),
        migrations.AlterField(
            model_name='flower',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flowers', to='flowers.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(default=1, upload_to='flowers/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
