# Generated by Django 5.2.4 on 2025-08-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0009_remove_flower_in_stock_alter_flower_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
    ]
