# Generated by Django 5.2.4 on 2025-08-08 12:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0010_flower_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Условия работы', max_length=200, verbose_name='Заголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст условий работы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Условия работы',
                'verbose_name_plural': 'Условия работы',
            },
        ),
    ]
